sudo: required
services:
  - docker

before_install:
  - docker build -t milan320/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true milan320/docker-react npm run test

language: generic

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-065520633212"
  bucket_path: "docker-react"
  on: 
    branch: master
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"  



